# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".idea",
    ".venv",
    ".vscode",
    ".ruff_cache",
    "__pycahce__",
    "configs",
    "scritps",
    "release",
]
line-length = 120
indent-width = 4

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true

[lint]
ignore = ["E501"]
